[package]
name = "afseq"
version = "0.1.0"
edition = "2018"
description = "afplay sequencer"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "player", "sequencer"]

[dependencies]
paste = { version = "1.0.9"}
rust-music-theory = { version = "0.2.0" }
rhai = { version = "1.10.1", optional = true, features = ["metadata"] }
rhai-sci = { version = "0.1", optional = true }       

[dev-dependencies]
afplay = { path = "../afplay", default-features = false, features = ["cpal-output"] }
notify = { version = "5.0.0" }
lazy_static = { version = "1.4.0" }

[profile.release]
debug = 1

[features]
scripting = ["rhai", "rhai-sci"]
default = ["scripting"]

[[example]]
name = "play"
[[example]]
name = "play-script"
required-features = ["scripting"]