[package]
name = "afseq"
version = "0.1.0"
edition = "2018"
description = "afplay sequencer"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "player", "sequencer"]

[dev-dependencies]
afplay = { path = "../afplay", default-features = false, features=["cubeb-output"] }

[[examples]]
name = "play-sequence"
