[package]
name = "afseq"
version = "0.1.0"
edition = "2018"
description = "afplay sequencer"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "player", "sequencer"]

[dependencies]
paste = { version = "1.0.9"}
derive_more = { version = "0.99.17" }
crossbeam-channel = { version = "0.5.6" }
rust-music-theory = { version = "0.2.0" }
rhai = { version = "1.10.1", optional = true, features = ["metadata", "internals"] }
rhai-sci = { version = "0.1.7", optional = true }       
rhai-rand = { version = "0.1.4", optional = true }
afplay = { path = "../afplay", default-features = false, features = ["cpal-output"], optional = true }

[dev-dependencies]
notify = { version = "5.0.0" }
lazy_static = { version = "1.4.0" }

[profile.release]
debug = 1

[features]
scripting = ["rhai", "rhai-sci", "rhai-rand"]
player = ["afplay"]
default = ["scripting", "player"]

[[example]]
name = "play"
required-features = ["player"]
[[example]]
name = "play-script"
required-features = ["scripting", "player"]