[package]
name = "afseq"
version = "0.1.0"
edition = "2021"
description = "afplay sequencer"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "player", "sequencer"]

[dependencies]
# required
lazy_static = { version = "^1.4" }
anyhow = { version = "^1.0" }
paste = { version = "^1.0"}
derive_more = { version = "^0.99" }
crossbeam-channel = { version = "^0.5" }
log = { version = "^0.4" }
simplelog = { version = "^0.12" }
serde = { version = "^1.0" }
serde_json = { version = "^1.0" }
uuid = {version = "^1.3", features = [ "v4", "fast-rng" ]}
rust-music-theory = { version = "^0.2" }
# optional -> dhat-profiler
dhat = { version = "0.3.2", optional = true }
# optional -> scripting
mlua = { version = "^0.9", features = ["lua52", "vendored", "macros", "unstable"], optional = true }
# optional -> player
afplay = { path = "../afplay", default-features = false, features = ["cpal-output"], optional = true }

[dev-dependencies]
notify = { version = "^6.1" }
ctrlc = { version = "3.4.0"}

[profile.release]
debug = 1

[features]
dhat-profiler = ["dhat"]
scripting = ["mlua"]
player = ["afplay"]
default = ["scripting"]

[[example]]
name = "play"
required-features = ["player"]

[[example]]
name = "play-script"
required-features = ["scripting", "player"]
