[package]
name = "afseq"
version = "0.1.0"
edition = "2018"
description = "afplay sequencer"
authors = ["Eduard Müller <mail@emuell.net>"]
exclude = ["assets", "examples"]
categories = ["audio", "player", "sequencer"]

[dependencies]
paste = { version = "^1.0"}
derive_more = { version = "^0.99" }
crossbeam-channel = { version = "^0.5" }
log = { version = "^0.4" }
simplelog = { version = "^0.12" }
string-error = { version = "^0.1" }
serde = { version = "^1.0" }
serde_json = { version = "^1.0" }
uuid = {version = "^1.3", features = [ "v4", "fast-rng" ]}
rust-music-theory = { version = "^0.2" }
rhai = { version = "^1.13", optional = true, features = ["metadata", "internals", "serde"] }
rhai-rand = { version = "^0.1", optional = true }
afplay = { path = "../afplay", default-features = false, features = ["cpal-output"], optional = true }

[dev-dependencies]
notify = { version = "^5.1" }
lazy_static = { version = "^1.4" }

[profile.release]
debug = 1

[features]
scripting = ["rhai", "rhai-rand"]
player = ["afplay"]
default = ["scripting", "player"]

[[example]]
name = "play"
required-features = ["player"]
[[example]]
name = "play-script"
required-features = ["scripting", "player"]