[package]
name = "generate-api-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
# { path = "../../../luals-docs-gen" }
luals-docs-gen = { git = "https://github.com/emuell/luals-docs-gen", tag = "v0.1.0" }
