name: Build & Deploy Docs

on:
  push:
    branches: [ "master" ]
  # allow running the workflow from the actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          cache-workspaces: "docs"
          cache-key: "pattrns-pages"

      - name: Install mdbook
        run: cargo install mdbook mdbook-linkcheck mdbook-toc mdbook-alerts

      - name: Generate API
        run: cd docs && cargo run

      - name: Build Book
        run: cd docs && mdbook build

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./docs/out/html
          
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
